#!/bin/sh

filename=$1.chpl;
echo "Compiling '$filename'";
# start_time=`date +%s`;


if chpl --fast -M lib -I/opt/homebrew/opt/openblas/include -L/opt/homebrew/opt/openblas/lib -lblas $filename --output=build/$1 ; then
    # end_time=`date +%s`
    # echo "execution time was `expr $end_time - $start_time` s.";
    echo "Running 'build/$1'";
    ./build/$1;
    
else
    echo "Build failed";
fi


# echo "Username: $username";
# echo "Age: $age";
# echo "Full Name: $fullname";